PersonelUI/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Entities.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PersonelUI.Areas.Admin.Models;

namespace PersonelUI.Areas.Admin.Controllers
{
    [Area("admin")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
        private readonly SignInManager<AppUser> _signInManager;

        public UserController(
            UserManager<AppUser> userManager,
            RoleManager<AppRole> roleManager,
            SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }


        public IActionResult Index()
        {
            return View();
        }
        /* ROLE EKLEME ALTYAPISI
         public async Task<IActionResult> Index()
        {
            var user = new AppRole
            {
                Name="support",
                NormalizedName="SUPPORT",
                ConcurrencyStamp= Guid.NewGuid().ToString()
            };
            await _roleManager.CreateAsync(user);
            return View();

        }
             */
        public IActionResult Add()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(UserAddVm data)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser
                {
                    FirstName = data.FirstName,
                    LastName = data.LastName,
                    Email = data.Email,
                    UserName = data.UserName,
                    BirthDay = DateTime.Now.AddDays(-20)
                };

                await _userManager.CreateAsync(user, data.Password);
                await _userManager.AddToRoleAsync(user, data.RoleName);
            }
            return View();
        }
    }
}

PersonelUI/Areas/Editor/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Context;
using Entities.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonelUI.Areas.Editor.Models;

namespace PersonelUI.Areas.Editor.Controllers
{
    [Authorize(Roles = "admin,editor")]
    [Area("editor")]
    public class GameController : Controller
    {
        private readonly GamePlatformDbContext _context;

        public GameController(GamePlatformDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context.Games
                .Include(game => game.Developer)
                .Include(game => game.GameCategories)
                    .ThenInclude(gc => gc.Category)
                .ToList();

            return View(model);
        }

        public IActionResult Add()
        {
            var model = new GameAddGetVm
            {
                Companies = _context.Companies.ToList(),
                Categories = _context.Categories.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(GameAddPostVm data)
        {
            _context.Games.Add(new Game
            {
                GameName = data.GameName,
                DeveloperId = data.DeveloperId,
                IsSafeContent = true,
                PublisherId = data.PublisherId,
                IsActive = true,
                AddedDate = DateTime.Now,
                Price = data.Price,
                PublishDate = DateTime.Now.AddYears(-5)
            });

            _context.SaveChanges();

            var lastGameId = _context.Games
                .OrderByDescending(o => o.AddedDate)
                .FirstOrDefault()
                .Id;

            foreach (var categoryId in data.Categories)
            {
                _context.GameCategories.Add(new GameCategory
                {
                    GameId = lastGameId,
                    CategoryId = categoryId,
                    IsGenre = true
                });
            }

            _context.SaveChanges();

            return Json("Oyun başarıyla eklendi.");
        }

        public IActionResult MakeDiscount(int id)
        {
            var game = _context.Games.Find(id);

            return View(new MakeDiscountVm
            {
                GameId = game.Id,
                CurrentPrice = game.Price
            });
        }

        [HttpPost]
        public async Task<IActionResult> MakeDiscount(int gameId, decimal discountPrice)
        {
            var game = _context.Games.Find(gameId);
            game.DiscountPrice = discountPrice;
            _context.Update(game);
            await _context.SaveChangesAsync();

            return Json("İndirim uygulandı.");
        }

        public async Task<IActionResult> RemoveDiscount(int gameId)
        {
            var game = _context.Games.Find(gameId);
            game.DiscountPrice = null;
            _context.Update(game);
            await _context.SaveChangesAsync();

            return Json("İndirim kaldırıldı.");
        }
    }
}

PersonelUI/Areas/Support/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Context;
using Entities.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonelUI.Areas.Support.Models;

namespace PersonelUI.Areas.Support.Controllers
{
    [Area("support")]
    [Authorize(Roles = "admin,support")]
    public class TicketController : Controller
    {
        private readonly GamePlatformDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public TicketController(GamePlatformDbContext context,
            UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index(string status)
        {
            var baseModel = _context.SupportTicket
                .Include(st => st.SupportTicketCategory)
                .Include(st => st.IssuedUser)
                .Include(st => st.FixedUser);

            List<SupportTicket> model;

            switch (status)
            {
                case "all":
                case null:
                    model = baseModel.ToList();
                    break;
                case "unanswered":
                    model = baseModel.Where(x => x.IsSolved == null).ToList();
                    break;
                default:
                    model = baseModel.ToList();
                    break;
            }

            return View(model);
        }

        public IActionResult Details(int ticketId)
        {
            var ticket = _context.SupportTicket.FirstOrDefault(x => x.Id == ticketId);

            var relatedSteps = _context.SupportTicketSteps
                .Where(x => x.SupportTicketId == ticketId)
                .Include(sts => sts.SupportTicket)
                .Include(sts => sts.AnsweredUser)
                .ToList();

            var model = new TicketDetailsVm
            {
                SupportTicket = ticket,
                SupportTicketSteps = relatedSteps
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AnswerTicket(TicketAnswerVm data)
        {

            _context.SupportTicketSteps.Add(new SupportTicketStep
            {
                AddedDate = DateTime.Now,
                AnsweredUserId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id,
                Content = data.Content,
                SupportTicketId = data.TicketId,
                IsActive = true
            });

            await _context.SaveChangesAsync();

            return Json("Cevap iletildi");
        }
    }
}

PersonelUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Game Platform</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Game Platform</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                        @if (User.IsInRole("admin"))
                        {
                            <li><a asp-area="Admin" asp-controller="User" asp-action="Index">Admin Panel</a></li>
                        }
                        @if (User.IsInRole("editor") || User.IsInRole("admin"))
                        {
                            <li><a asp-area="Editor" asp-controller="Game" asp-action="Index">Editor Sayfası</a></li>
                        }
                        @if (User.IsInRole("support") || User.IsInRole("admin"))
                        {
                            <li><a asp-area="Support" asp-controller="Ticket" asp-action="Index">Destek birimi</a></li>
                        }
                        <li><a asp-area="" asp-controller="Account" asp-action="SignOut">Çıkış Yap</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content" style="margin-top: 2%;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Game Platform</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>